<?php
/**
 * Link Analyzer - Applies fixes to broken links
 * 
 * @package SEOAutoFix\BrokenUrlManagement
 */

namespace SEOAutoFix\BrokenUrlManagement;

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Link Analyzer Class
 */
class Link_Analyzer
{

    /**
     * Database manager
     */
    private $db_manager;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->db_manager = new Database_Manager();
    }

    /**
     * Apply fixes for selected broken links
     * 
     * @param array $entry_ids Entry IDs to fix
     * @param string $custom_url Optional custom URL to use for replacement
     * @return array Result with counts
     */
    public function apply_fixes($entry_ids, $custom_url = '')
    {
        error_log('[APPLY_FIXES] Starting with entry IDs: ' . print_r($entry_ids, true));
        error_log('[APPLY_FIXES] Custom URL provided: ' . $custom_url);

        $fixed_count = 0;
        $failed_count = 0;
        $skipped_count = 0;
        $messages = array();

        foreach ($entry_ids as $entry_id) {
            error_log('[APPLY_FIXES] Processing entry ID: ' . $entry_id);

            // Get entry details
            $entry = $this->db_manager->get_entry($entry_id);

            if (!$entry) {
                error_log('[APPLY_FIXES] Entry not found: ' . $entry_id);
                $failed_count++;
                $messages[] = sprintf(
                    __('Entry #%d not found', 'seo-autofix-pro'),
                    $entry_id
                );
                continue;
            }

            error_log('[APPLY_FIXES] Entry data: ' . print_r($entry, true));

            // Check if this is a template-generated link that can't be fixed
            if ($this->is_template_generated_link($entry['broken_url'])) {
                error_log('[APPLY_FIXES] Skipping template-generated link: ' . $entry['broken_url']);
                $skipped_count++;
                $messages[] = sprintf(
                    __('⚠️ Cannot fix: %s - This link is generated by WordPress theme/templates. Please fix it in your theme files or comment settings.', 'seo-autofix-pro'),
                    esc_url($entry['broken_url'])
                );
                continue;
            }

            // Determine replacement URL priority: custom_url > user_modified_url > suggested_url
            $replacement_url = '';
            
            if (!empty($custom_url)) {
                $replacement_url = $custom_url;
                error_log('[APPLY_FIXES] Using custom URL from parameter: ' . $replacement_url);
            } elseif (!empty($entry['user_modified_url'])) {
                $replacement_url = $entry['user_modified_url'];
                error_log('[APPLY_FIXES] Using user_modified_url from database: ' . $replacement_url);
            } elseif (!empty($entry['suggested_url'])) {
                $replacement_url = $entry['suggested_url'];
                error_log('[APPLY_FIXES] Using suggested_url from database: ' . $replacement_url);
            }

            // If still no replacement URL and it's external, skip (only if no custom URL provided)
            if (empty($replacement_url)) {
                if ($entry['link_type'] === 'external') {
                    error_log('[APPLY_FIXES] Skipping external link with no replacement: ' . $entry['broken_url']);
                    $skipped_count++;
                    $messages[] = sprintf(
                        __('⚠️ Skipped external link: %s (manual intervention required)', 'seo-autofix-pro'),
                        esc_url($entry['broken_url'])
                    );
                    continue;
                }
                
                error_log('[APPLY_FIXES] No replacement URL available for: ' . $entry['broken_url']);
                $failed_count++;
                $messages[] = sprintf(
                    __('❌ No replacement URL for: %s', 'seo-autofix-pro'),
                    esc_url($entry['broken_url'])
                );
                continue;
            }

            // Apply fix to the content
            error_log('[APPLY_FIXES] Attempting to replace link in content. Found on: ' . $entry['found_on_url'] . ', Broken: ' . $entry['broken_url'] . ', Replacement: ' . $replacement_url);

            $success = $this->replace_link_in_content(
                $entry['found_on_url'],
                $entry['broken_url'],
                $replacement_url
            );

            error_log('[APPLY_FIXES] Replace link result: ' . ($success ? 'SUCCESS' : 'FAILED'));

            if ($success) {
                $fixed_count++;
                $mark_result = $this->db_manager->mark_as_fixed($entry_id);
                error_log('[APPLY_FIXES] Mark as fixed result for ID ' . $entry_id . ': ' . ($mark_result ? 'SUCCESS' : 'FAILED'));

                // Log activity for reporting
                global $wpdb;
                $table_activity = $wpdb->prefix . 'seoautofix_broken_links_activity';
                
                error_log('[ACTIVITY LOG] Attempting to log fix/replace activity for ID: ' . $entry_id);
                error_log('[ACTIVITY LOG] Scan ID: ' . $entry['scan_id']);
                error_log('[ACTIVITY LOG] Broken URL: ' . $entry['broken_url']);
                error_log('[ACTIVITY LOG] Replacement URL: ' . $replacement_url);
                error_log('[ACTIVITY LOG] Action type: ' . ($custom_url ? 'replaced' : 'fixed'));
                
                $insert_result = $wpdb->insert($table_activity, array(
                    'scan_id' => $entry['scan_id'],
                    'entry_id' => $entry_id,
                    'broken_url' => $entry['broken_url'],
                    'replacement_url' => $replacement_url,
                    'action_type' => $custom_url ? 'replaced' : 'fixed',
                    'page_url' => $entry['found_on_url'],
                    'page_title' => $entry['found_on_page_title']
                ), array('%s', '%d', '%s', '%s', '%s', '%s', '%s'));
                
                if ($insert_result === false) {
                    error_log('[ACTIVITY LOG ERROR] Failed to insert activity log! wpdb error: ' . $wpdb->last_error);
                    error_log('[ACTIVITY LOG ERROR] wpdb last_query: ' . $wpdb->last_query);
                } else {
                    error_log('[ACTIVITY LOG SUCCESS] Activity log entry created with ID: ' . $wpdb->insert_id);
                }

                $messages[] = sprintf(
                    __('✅ Fixed: %s → %s', 'seo-autofix-pro'),
                    esc_url($entry['broken_url']),
                    esc_url($replacement_url)
                );
            } else {
                $failed_count++;
                $messages[] = sprintf(
                    __('❌ Failed to fix: %s - Link not found in post content', 'seo-autofix-pro'),
                    esc_url($entry['broken_url'])
                );
            }
        }

        error_log('[APPLY_FIXES] Completed. Fixed: ' . $fixed_count . ', Failed: ' . $failed_count . ', Skipped: ' . $skipped_count);

        return array(
            'fixed_count' => $fixed_count,
            'failed_count' => $failed_count,
            'skipped_count' => $skipped_count,
            'messages' => $messages
        );
    }

    /**
     * Replace link in post/page content
     * 
     * @param string $page_url Page where link was found
     * @param string $broken_url Broken URL to replace
     * @param string $replacement_url New URL
     * @return bool Success
     */
    private function replace_link_in_content($page_url, $broken_url, $replacement_url)
    {
        error_log('[REPLACE_LINK] Starting. Page URL: ' . $page_url . ', Broken: ' . $broken_url . ', Replacement: ' . $replacement_url);

        // Get post ID from URL
        $post_id = url_to_postid($page_url);

        error_log('[REPLACE_LINK] Post ID from URL: ' . $post_id);

        if (!$post_id) {
            error_log('[REPLACE_LINK] Failed to get post ID from URL');
            return false;
        }

        // Get post content
        $post = get_post($post_id);

        if (!$post) {
            error_log('[REPLACE_LINK] Failed to get post object for ID: ' . $post_id);
            return false;
        }

        error_log('[REPLACE_LINK] Got post. Title: ' . $post->post_title . ', Content length: ' . strlen($post->post_content));

        $content = $post->post_content;
        
        // Normalize URLs - remove trailing slashes for comparison
        $normalized_broken = untrailingslashit($broken_url);
        $normalized_replacement = untrailingslashit($replacement_url);
        
        error_log('[REPLACE_LINK] Original broken URL: ' . $broken_url);
        error_log('[REPLACE_LINK] Normalized broken URL: ' . $normalized_broken);
        
        // Multiple patterns to catch different URL formats in HTML
        // This handles: trailing slashes, HTML entities, different quote styles, plain text
        $patterns = array();
        $replacements = array();
        
        // Pattern 1: Standard href with double quotes - exact match
        $patterns[] = '/href="' . preg_quote($broken_url, '/') . '"/i';
        $replacements[] = 'href="' . esc_url($replacement_url) . '"';
        
        // Pattern 2: Standard href with single quotes - exact match
        $patterns[] = "/href='" . preg_quote($broken_url, '/') . "'/i";
        $replacements[] = 'href="' . esc_url($replacement_url) . '"';
        
        // Pattern 3: Standard src with double quotes - exact match
        $patterns[] = '/src="' . preg_quote($broken_url, '/') . '"/i';
        $replacements[] = 'src="' . esc_url($replacement_url) . '"';
        
        // Pattern 4: Standard src with single quotes - exact match
        $patterns[] = "/src='" . preg_quote($broken_url, '/') . "'/i";
        $replacements[] = 'src="' . esc_url($replacement_url) . '"';
        
        // Pattern 5: href with optional trailing slash (normalized version)
        $patterns[] = '/href="' . preg_quote($normalized_broken, '/') . '\/?"/i';
        $replacements[] = 'href="' . esc_url($replacement_url) . '"';
        
        // Pattern 6: href with single quotes and optional trailing slash
        $patterns[] = "/href='" . preg_quote($normalized_broken, '/') . '\/?' . "'/i";
        $replacements[] = 'href="' . esc_url($replacement_url) . '"';
        
        // Pattern 7: src with optional trailing slash (normalized version)
        $patterns[] = '/src="' . preg_quote($normalized_broken, '/') . '\/?"/i';
        $replacements[] = 'src="' . esc_url($replacement_url) . '"';
        
        // Pattern 8: src with single quotes and optional trailing slash
        $patterns[] = "/src='" . preg_quote($normalized_broken, '/') . '\/?' . "'/i";
        $replacements[] = 'src="' . esc_url($replacement_url) . '"';
        
        // Pattern 9: HTML entity quotes (&quot;) - exact match
        $patterns[] = '/href=&quot;' . preg_quote($broken_url, '/') . '&quot;/i';
        $replacements[] = 'href=&quot;' . esc_url($replacement_url) . '&quot;';
        
        // Pattern 10: HTML entity quotes for src
        $patterns[] = '/src=&quot;' . preg_quote($broken_url, '/') . '&quot;/i';
        $replacements[] = 'src=&quot;' . esc_url($replacement_url) . '&quot;';
        
        // Pattern 11: HTML entity quotes with optional trailing slash
        $patterns[] = '/href=&quot;' . preg_quote($normalized_broken, '/') . '\/?&quot;/i';
        $replacements[] = 'href=&quot;' . esc_url($replacement_url) . '&quot;';
        
        // Pattern 12: Plain text URL (not in attributes) - be careful with this one
        // Only match if not preceded by quote or equals
        $patterns[] = '/(?<!["\'=>])' . preg_quote($broken_url, '/') . '(?!["\'])/i';
        $replacements[] = esc_url($replacement_url);
        
        error_log('[REPLACE_LINK] Using ' . count($patterns) . ' patterns for flexible matching');

        $new_content = preg_replace($patterns, $replacements, $content);

        // Check if replacement was made
        if ($new_content === $content) {
            // No changes made with regex, try simple string replacement as fallback
            error_log('[REPLACE_LINK] Regex patterns did not match, trying simple string replace');
            
            // Try exact string replacement
            $new_content = str_replace($broken_url, $replacement_url, $content);
            
            // If still no match, try without trailing slash
            if ($new_content === $content && $broken_url !== $normalized_broken) {
                error_log('[REPLACE_LINK] Trying normalized URL without trailing slash');
                $new_content = str_replace($normalized_broken, $normalized_replacement, $content);
            }
            
            // Final check
            if ($new_content === $content) {
                error_log('[REPLACE_LINK] No changes made - link not found in content in any format');
                error_log('[REPLACE_LINK] Content preview: ' . substr($content, 0, 500));
                return false;
            }
        }

        error_log('[REPLACE_LINK] Content changed. Old length: ' . strlen($content) . ', New length: ' . strlen($new_content));

        // Update post
        $result = wp_update_post(array(
            'ID' => $post_id,
            'post_content' => $new_content
        ), true);

        error_log('[REPLACE_LINK] wp_update_post result: ' . print_r($result, true) . ', is_wp_error: ' . (is_wp_error($result) ? 'YES' : 'NO'));

        return !is_wp_error($result);
    }

    /**
     * Check if a link is template-generated and cannot be fixed programmatically
     * 
     * @param string $url The URL to check
     * @return bool True if template-generated
     */
    private function is_template_generated_link($url)
    {
        // Common patterns for template-generated links
        $template_patterns = array(
            '#respond',              // Comment reply links
            '#comment-',             // Comment anchors
            '/wp-admin/',           // Admin links
            '/wp-login.php',        // Login links
            '/wp-comments-post.php', // Comment form actions
            '/feed/',               // Feed links
            '?replytocom=',         // Reply to comment parameter
        );

        foreach ($template_patterns as $pattern) {
            if (strpos($url, $pattern) !== false) {
                error_log('[IS_TEMPLATE_GENERATED] URL contains pattern: ' . $pattern);
                return true;
            }
        }

        return false;
    }

    /**
     * Get statistics for scan results
     * 
     * @param string $scan_id Scan ID
     * @return array Statistics
     */
    public function get_scan_statistics($scan_id)
    {
        global $wpdb;

        $table_results = $wpdb->prefix . 'seoautofix_broken_links_scan_results';

        $stats = array(
            'total_broken' => 0,
            'internal_broken' => 0,
            'external_broken' => 0,
            'fixed' => 0,
            'pending' => 0
        );

        // Get total broken links
        $stats['total_broken'] = $wpdb->get_var(
            $wpdb->prepare(
                "SELECT COUNT(*) FROM {$table_results} 
                WHERE scan_id = %s AND is_deleted = 0",
                $scan_id
            )
        );

        // Get internal broken links
        $stats['internal_broken'] = $wpdb->get_var(
            $wpdb->prepare(
                "SELECT COUNT(*) FROM {$table_results} 
                WHERE scan_id = %s AND is_deleted = 0 AND link_type = 'internal'",
                $scan_id
            )
        );

        // Get external broken links
        $stats['external_broken'] = $wpdb->get_var(
            $wpdb->prepare(
                "SELECT COUNT(*) FROM {$table_results} 
                WHERE scan_id = %s AND is_deleted = 0 AND link_type = 'external'",
                $scan_id
            )
        );

        // Get fixed links
        $stats['fixed'] = $wpdb->get_var(
            $wpdb->prepare(
                "SELECT COUNT(*) FROM {$table_results} 
                WHERE scan_id = %s AND is_fixed = 1",
                $scan_id
            )
        );

        // Get pending links
        $stats['pending'] = $stats['total_broken'] - $stats['fixed'];

        return $stats;
    }
}
